### PR TITLE
Really appreciated that you create this project, and I have added some features.

### PR DESCRIPTION
**Pull request by xiaoxuhuanxiang**
Hi @AngelDTF,

I've made some updates to the OpenParsec project and would like to submit a PR for your review. Here's a summary of the changes:

    1. Add a circle queue to manage buffer, and add silence buffer, 
        to eliminate the latency of sound.
    2. Improve the performance of video, it was not fluent when you turn
       around camera in a 3A game fastly, which is much worse than my Android
       phone(iPhone 12PM vs Motorola edge S30). And after the improvement, I
       think my iPhone12PM is much better than my Android phone.
    3. Add game controller support, tested with Dualshock5. But only one
       controller is supported so far, because I don't need more. I don't know 
       whether it supports other kind of game controller, and I guess it will work, 
       assuming that your game controller does connect to your iPhone/iPad normally.
    4. Add the H265 support, also there is a toggle button, when you touch
       the parsec icon you will see it.
    5. Use the safe area, it can play bigger than before, especially when
       the host has a 2778*1284 (for my iPhone 12PM) resolution, the iPhone
       12PM can run fully screen.
    6. Add the decode latency, the encode latency, the network latency, 
       the video bitrate, the stream format, the resolution, the decode method
       (eg. software or hardware) info, just like the windows and android
       client, when you touch the icon, it will appear on the top of screen.
       And it only updates every one second, because I really worried about
       the efficiency.

   PS: My English is poor, I hope that you can understand what I am saying, and this is my first time to contribute code in github, 
         if you have any questions, please contact me.
  
  Best Regards
  @xiaoxuhuanxiang

### CODE REVIEW

**Comment by LinusJun** [comment]
Awesome！Game controller backbone one with ipad mini 6 works perfect! Connected after open Openparsec app. Thanks

**Comment by xiaoxuhuanxiang** [comment]
> Awesome！Game controller backbone one with ipad mini 6 works perfect! Connected after launch Openparsec app. Thanks
I am so glad to hear that ! Have fun !!  ^_^

**Comment by xiaoxuhuanxiang** [comment]
> Awesome！Game controller backbone one with ipad mini 6 works perfect! Connected after launch Openparsec app. Thanks


Hey @LinusJun 

     Some new changes were made about the game controller, the new version no longer has the limitation that the OpenParsec app must be launched before connecting the controller. The controller can be used whenever it is connected. You can try it whenever you want.

**Comment by AngelDTF** [comment]
Hey @xiaoxuhuanxiang, thanks for your interest in the project and for taking the time to add more features. I'll be sure to review the code tomorrow to see if I can get this merged ASAP.

**Comment by NeroShooter** [comment]
Hi, no controller is detected on my iPhone 15 Pro Max. Tested with DualShock 5, both via bluetooth and USB, and Backbone. I'm using Parsec on an M2 MacBook Pro. Any suggestion?

**Comment by AngelDTF** [comment]
I don't have access to a DualShock 5 controller, I won't be able to replicate it. If you have any other controllers, you could try to see if any of them work. A DualShock 4 controller worked for me over Bluetooth on iOS 13.6.1, haven't tested with a newer iOS.

**Comment by xiaoxuhuanxiang** [comment]
> Hi, no controller is detected on my iPhone 15 Pro Max. Tested with DualShock 5, both via bluetooth and USB, and Backbone. I'm using Parsec on an M2 MacBook Pro. Any suggestion?

Have you tested any other apps with DualShock 5 ?  
I haven't tested on a newer IOS either, I tested it on IOS 14.5.

**Comment by NeroShooter** [comment]
I tested both DS5 and Backbone with PS Remote Play and Steam Link.

Remote Play works perfectly. As for Steam Link, I can control the menus in Big Picture, but as soon as I launch any game the controllers are not detected. 

Therefore I reckon the issue might be linked with the fact that I use a Silicon Mac rather than I use a more recent version of iOS.

**Comment by AngelDTF** [comment]
Ah, I didn't think of that. The device I connected my phone to was a Windows machine, and I currently do not have a Silicon Mac to test with.

**Pull request merged**
