### PR TITLE
Many changes were made.

### PR DESCRIPTION
**Pull request by LeaveNhA**
I don't have much to say, I might gonna start documenting the whole sh*t by myself, but bro, I would really use one more pair of hand because iOS, Swift, these are so distant to me. I barely added a functionality in not a practical time (maybe hours?).

I appreciate your efforts and help on this. Good luck!

### CODE REVIEW

**Comment by LeaveNhA** [comment]
There are some conflicts, you did the last one, please, I will clear my mess.

**Comment by AngelDTF** [comment]
Apologies for not being able to take a look at this sooner, I was recovering from another health incident. I'm assuming you want me to look through all of these except the 2FA ones since I handled those already (correct me if I'm wrong). I'll take a look at it tomorrow, but due to the conflicts I believe I'm going to have to manually merge everything once my checks pass. Also, Swift is pretty distant to me to since I'm rather new to coding for iOS, but I really appreciate any help I can get.

**Comment by AngelDTF** [comment]
I have manually merged this PR in commit 2e52444b66432401b58857a4e8a77d0c28e2dc83. Thanks again for your contributions!

**Comment by LeaveNhA** [comment]
I'm sorry that my attention has been stolen by my rushy implementation on BabyAGI.
I'm still thinking about adding Controller support. I believe we must focus on quantity first, then we can focus on quality.
By this mentality, soon, I might start with implementing Controller support into this and also think that it would be much more easy than that. 🙏🏻

Thanks again for your time and effort @AngelDTF! 🎉

**Comment by AngelDTF** [comment]
It's all good. In all honesty, I should be thanking you. You've sped up production of a project I didn't even think I'd finish. Even if this project won't last forever due to the use of an SDK that is no longer receiving updates, I'm still happy to be working on it with somebody that is passionate about their work.

I'm also going to be adding some more features to allow this app to be as close to a full-fledged client as possible, since I now know of some undocumented API URLs by using the Network tab in the Chrome developer tools. My hope is that this app can be finished and be useful for some time before it inevitably stops working.

**Comment by LeaveNhA** [comment]
I understand your concerns, I believe we can keep update the SDK as far as we can. Since they releases on Andriod type of targets, we can reverse-engineer the clients and keep up. Also I believe, they can't publish some breaking changes soon. But my perspective is so fragile, with their latest associations, they might change their angel over the product.
I believe we can gather some few but decent people as commumity and work on it collaboratively. As a community we can move forward. 

Thank you again, for everything! 🙋🏻‍♂️

**Comment by Exceen** [comment]
Is it possible to bring up the keyboard? I noticed the `KeyboardViewController`, what does it do?

**Comment by AngelDTF** [comment]
IIRC it only has limited functionality at the moment, only being able to communicate with an external keyboard. I'm rather busy at the moment, but when I have time, I plan on adding a show keyboard button to the overlay dropdown.

**Pull request closed without merging**
